
title: Applied Statistics - Notes
author: Carlos Ramirez Villamarin
# logo: logo.png  # optional

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/carlosrv19/academic-notes  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # favicon: images/favicon.ico
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  
